eureka:
  client:
    register-with-eureka: true
    fetch-registry: true #// register with server
    service-url:
      defaultzone: http://localhost:8761/eureka
      instance:
        hostname: localhost
